version: "3.9"

services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      #- SERVER_REGIONS=US Houston
    networks:
      - mynetwork
    ports:
      # qBittorrent Ports
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"
  
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    # Comment this if vpn is disabled
    depends_on:
      - vpn
    networks:
      - mynetwork
    network_mode: service:vpn # Comment this line if vpn is disabled
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - mynetwork
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    networks:
      - mynetwork
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    networks:
      - mynetwork
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
    ports:
      - 5055:5055
    volumes:
      - overseerr-config:/app/config
    restart: unless-stopped
    

volumes:
  qbittorrent-config:
  torrent-downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.112,rw,vers=4.1
      device: ":/volume1/media/"
  radarr-config:
  jackett-config:
  jackett-blackhole:
  sonarr-config:
  overseerr-config:

networks:
  mynetwork:
    driver: bridge
    #external: true