version: "3.9"

services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      #- SERVER_REGIONS=US Houston
    networks:
      - mynetwork
    ports:
      # qBittorrent Ports
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"
  
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    # Comment this if vpn is disabled
    depends_on:
      - vpn
    # Commenting this because it breaks watchtower
    #networks:
    #  - mynetwork
    network_mode: service:vpn # Comment this line if vpn is disabled
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - media-downloads:/downloads
    restart: "unless-stopped"
  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    networks:
      - mynetwork
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /path/to/data:/config
      - media-downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - mynetwork
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - media-downloads:/downloads
    restart: "unless-stopped"

  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    networks:
      - mynetwork
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - sonarr-config:/config
      - media-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    networks:
      - mynetwork
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
    ports:
      - 5055:5055
    volumes:
      - overseerr-config:/app/config
    restart: unless-stopped
    
  flame:
    image: pawelmalak/flame
    container_name: flame
    networks:
      - mynetwork
    volumes:
      - flame-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 80:5005
    environment:
      - PASSWORD=${FLAME_PASSWORD}
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - mynetwork
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - lidarr-config:/config
      - media-downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  watchtower:      
    image: containrrr/watchtower:latest
    container_name: watchtower
    networks:
      - mynetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    networks:
      - mynetwork
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - calibre-web-config:/config
      - media-books:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    networks:
      - mynetwork
    restart: always
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      ## General
      - LOG_LEVEL=INFO
      #- TEST_RUN=True
      #- SSL_VERIFICATION=False
      ## Features 
      - REMOVE_TIMER=10
      - REMOVE_FAILED=True
      - REMOVE_METADATA_MISSING=True
      - REMOVE_MISSING_FILES=True     
      - REMOVE_NO_FORMAT_UPGRADE=True
      - REMOVE_ORPHANS=True
      - REMOVE_SLOW=True
      - REMOVE_STALLED=True
      - REMOVE_UNMONITORED=True
      - MIN_DOWNLOAD_SPEED=100
      - PERMITTED_ATTEMPTS=3
      - NO_STALLED_REMOVAL_QBIT_TAG=Don't Kill
      - IGNORE_PRIVATE_TRACKERS=True
      ## Radarr
      - RADARR_URL=http://192.168.1.189:7878
      - RADARR_KEY=${DECLUTTARR_RADARR_KEY}
      ## Sonarr
      - SONARR_URL=http://192.168.1.189:8989
      - SONARR_KEY=${DECLUTTARR_SONARR_KEY}
      ## Lidarr
      - LIDARR_URL=http://192.168.1.189:8686
      - LIDARR_KEY=${DECLUTTARR_LIDARR_KEY}
      ## Readarr
      # - READARR_URL=http://readarr:8787
      # - READARR_KEY=$READARR_API_KEY
      ## qBittorrent
      - QBITTORRENT_URL=http://192.168.1.189:5080
      - QBITTORRENT_USERNAME=${DECLUTTARR_QBITTORRENT_USERNAME}
      - QBITTORRENT_PASSWORD=${DECLUTTARR_QBITTORRENT_PASSWORD}
    

volumes:
  qbittorrent-config:
  media-downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.112,rw,vers=4.1
      device: ":/volume1/media/"
  media-books:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.112,rw,vers=4.1
      device: ":/volume1/media/Books/"
  gitlab-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.112,rw,vers=4.1
      device: ":/volume1/media/Gitlab/"
  sabnzbd-config:
  radarr-config:
  jackett-config:
  jackett-blackhole:
  sonarr-config:
  overseerr-config:
  flame-data:
  lidarr-config:
  calibre-web-config:        
  #gitlab-config:
  #gitlab-logs:

networks:
  mynetwork:
    driver: bridge
    #external: true
