version: "3.8"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - VERSION=latest
      - TZ=America/Chicago
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/media:/data/media
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped